//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidTranslatorLibTest {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidTranslatorLibTest.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///    &lt;string name=&quot;keyboard_skin_id_default&quot;&gt;preference_keyboard_android_easy_to_read_black&lt;/string&gt;
        ///    &lt;string name=&quot;Orientation&quot;&gt;Портретная&lt;/string&gt;
        ///    &lt;string name=&quot;ime_name&quot;&gt;Big Buttons Keyboard Beta&lt;/string&gt;
        ///    &lt;string name=&quot;preference_bb_setting_app&quot;&gt;Big Buttons Keyboard Beta 4.0.1&lt;/string&gt;
        ///    &lt;string name=&quot;word_separators&quot;&gt;&quot; .,;:!?
        ///()[]*&amp;amp;@{}/&amp;amp;lt;&amp;amp;gt;_+=|&quot;&lt;/string&gt;
        ///    &lt;string name=&quot;label_go_key&quot;&gt;Go&lt;/string&gt;
        ///    &lt;string name=&quot;la [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string test_1_strings {
            get {
                return ResourceManager.GetString("test_1_strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///    &lt;string-array name=&quot;VoiceOptionsLayoutNames&quot;&gt;
        ///        &lt;item&gt;Google речь в текст&lt;/item&gt;
        ///        &lt;item&gt;Пользовательская речь в текст&lt;/item&gt;
        ///    &lt;/string-array&gt;
        ///    &lt;string-array name=&quot;VoiceOptionsLayout&quot;&gt;
        ///        &lt;item&gt;0&lt;/item&gt;
        ///        &lt;item&gt;1&lt;/item&gt;
        ///    &lt;/string-array&gt;
        ///    &lt;string-array name=&quot;KeyboardLayoutNames&quot;&gt;
        ///        &lt;item&gt;QWERTY (USA)&lt;/item&gt;
        ///        &lt;item&gt;QWERTZ&lt;/item&gt;
        ///        &lt;item&gt;AZERTY&lt;/item&gt;
        ///        &lt;item&gt;CYRILLIC&lt;/item&gt;
        ///        [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string test_2_arrays {
            get {
                return ResourceManager.GetString("test_2_arrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;translations name=&quot;AeDict&quot; version=&quot;1.0&quot;/&gt;.
        /// </summary>
        public static string test_3_dict {
            get {
                return ResourceManager.GetString("test_3_dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///    &lt;string name=&quot;test_string&quot;&gt;hello&lt;/string&gt;
        ///&lt;/resources&gt;.
        /// </summary>
        public static string test_3_strings {
            get {
                return ResourceManager.GetString("test_3_strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] test_4_log_smali {
            get {
                object obj = ResourceManager.GetObject("test_4_log_smali", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I: Using Apktool 2.2.1 on app-debug.apk
        ///I: Loading resource table...
        ///I: Decoding AndroidManifest.xml with resources...
        ///I: Loading resource table from file: C:\Users\Андрей\AppData\Local\apktool\framework\1.apk
        ///I: Regular manifest package...
        ///I: Decoding file-resources...
        ///I: Decoding values */* XMLs...
        ///I: Baksmaling classes.dex...
        ///I: Copying assets and libs...
        ///I: Copying unknown files...
        ///I: Copying original files...
        ///.
        /// </summary>
        public static string test_4_log_xml {
            get {
                return ResourceManager.GetString("test_4_log_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] test_5_AMapLocationClient {
            get {
                object obj = ResourceManager.GetObject("test_5_AMapLocationClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///    &lt;string name=&quot;~&quot;&gt;Navigate home&lt;/string&gt;
        ///    &lt;string name=&quot;!&quot;&gt;%1$s, %2$s&lt;/string&gt;
        ///    &lt;string name=&quot;@&quot;&gt;%1$s, %2$s, %3$s&lt;/string&gt;
        ///    &lt;string name=&quot;#&quot;&gt;Navigate up&lt;/string&gt;
        ///    &lt;string name=&quot;$&quot;&gt;More options&lt;/string&gt;
        ///    &lt;string name=&quot;%&quot;&gt;Done&lt;/string&gt;
        ///    &lt;string name=&quot;^&quot;&gt;See all&lt;/string&gt;
        ///    &lt;string name=&quot;&amp;amp;&quot;&gt;Choose an app&lt;/string&gt;
        ///    &lt;string name=&quot;(&quot;&gt;OFF&lt;/string&gt;
        ///    &lt;string name=&quot;)&quot;&gt;ON&lt;/string&gt;
        ///    &lt;string name=&quot;_&quot;&gt;Search…&lt;/string&gt;
        ///    &lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string test_6_strings {
            get {
                return ResourceManager.GetString("test_6_strings", resourceCulture);
            }
        }
    }
}
